version: '3'
services:
    odoo:
        container_name: odoo
        image: odoo:12.0
        depends_on:
            - db
        tty: true
        volumes:
            - ./etc:/etc/odoo
            - ./extra-addons:/mnt/extra-addons
            - odoo-data:/var/lib/odoo
        ports:
            - 8069:8069
            - 8072:8072
        restart: always
        networks:
            - odoo-network
    db:
        container_name: db
        image: mdillon/postgis
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data/pgdata
        networks:
            - odoo-network
volumes:
    odoo-data:
        driver: bridge
    db-data:
        driver: bridge
networks:
    odoo-network:
        driver: bridge